version: '3.8'

services:
  web:
    build: ./backend
    container_name: football_api
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    restart: always       
    networks:
      - liga

  db:
    image: postgres:15
    container_name: football_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: football_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres_backup:/backup  # Dodatkowy folder na backupy
    restart: always        
    networks:
      - liga

  frontend:
    build: 
      context: ./frontend
      args:
        VITE_API_URL: http://web:8000
    container_name: football_frontend
    ports:
      - "3000:80"
    depends_on:
      - web
    networks:
      - liga
  

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./postgres_data  # Lokalna ścieżka na serwerze

networks:
  liga:
