version: '3.8'

services:
  web:
    build: ./backend
    container_name: football_api
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - football_db
    networks:
      - liga

  football_db:
    image: postgres:15
    container_name: football_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: football_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d football_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - liga


volumes:
  postgres_data:

networks:
  liga:

