version: '3.8'

services:
  web:
    build: ./backend
    container_name: football_api
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    restart: always       
    networks:
      - liga

  db:
    image: postgres:15
    container_name: football_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: football_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always        
    networks:
      - liga

volumes:
  postgres_data:

networks:
  liga:
